### ISSUE TITLE
Modify 'January Utility'

### ISSUE THREAD

**Issue by carmentang** [carmentang/rental-registry#29]
Modify the following:

1. Take out the text field for 'January Utility'
2. Add an input field for 'January Utilities included in the rent (select all that apply)'. This will be a drop-down with the ability to select multiple options: ['electricity', 'gas', 'internet', 'parking', 'trash', 'water']
3. Add an input field for 'Additional charges from landlord, not included in rent (select all that apply). This will be a drop-down with the ability to select multiple options: ['electricity', 'gas', 'internet', 'parking', 'pet', 'trash', 'water']
4. Add text field for 'Total additional charges'
--> See https://xd.adobe.com/view/cd3db510-5642-450f-56bc-db59dd5da244-bb0c/screen/daff0019-876e-4c8c-8347-d9e2c1ca9240/Web-1920-7/ for a visual example of the above tasks.

**Comment by oilsinwater** [comment]
@karolina-benitez I am working with the state still between SingleUnit and Unit so knocked this out.
