### ISSUE TITLE
Modify 'Evictions' section

### ISSUE THREAD

**Issue by carmentang** [carmentang/rental-registry#31]
1. Separate out the sections 'Rent Increases' and 'Evictions'
2. In the evictions section, add a yes/no button selector with the question 'Was there a tenancy termination in this unit in the prior calendar year?'
3. If users select yes, then display a text field for 'Reason for tenancy termination' and another input field for 'Month of tenancy termination'
4. Add a button/link to 'Add additional tenancy termination'. If a user selects this, then an additional text field for 'Reason for tenancy termination' and input field for 'Month of tenancy termination'

--> See https://xd.adobe.com/view/cd3db510-5642-450f-56bc-db59dd5da244-bb0c/screen/daff0019-876e-4c8c-8347-d9e2c1ca9240/Web-1920-7/ for a visual example.

**Comment by oilsinwater** [comment]
@karolina-benitez @katiepantell will update you on where I am with this by tmrw noon.

**Comment by katiepantell** [comment]
> @karolina-benitez @katiepantell will update you on where I am with this by tmrw noon.

@oilsinwater awesome, thank you!

**Comment by oilsinwater** [comment]
Feel like I should wait to move forwards with this, so I am gonna hold off making any more changes to this until resolved...not sure if that makes sense, but lmk.
